# Generated by Django 5.2 on 2025-12-06 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('date', models.DateField(verbose_name='날짜')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='시작 시간')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('type', models.CharField(choices=[('personal', '개인 일정'), ('course', '강의 일정')], default='personal', max_length=20, verbose_name='일정 종류')),
                ('status', models.CharField(choices=[('planned', '예정'), ('done', '완료'), ('cancelled', '취소')], default='planned', max_length=20, verbose_name='상태')),
                ('course_id', models.IntegerField(blank=True, null=True, verbose_name='코스 ID')),
                ('course_name', models.CharField(blank=True, max_length=100, verbose_name='코스 이름')),
                ('course_color', models.CharField(blank=True, help_text='#RRGGBB 형식 (예: #FF6B6B)', max_length=7, verbose_name='코스 색상')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time', 'id'],
            },
        ),
    ]
