# Generated by Django 5.2 on 2025-12-06 01:51
# Generated by Django 5.2 on 2025-12-06 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='local_account', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('nickname', models.CharField(max_length=50)),
                ('account_type', models.CharField(default='local', max_length=20)),
                ('role', models.CharField(choices=[('SP', '학생/학부모'), ('MG', '매니저')], max_length=20)),
                ('solvedac_handel', models.CharField(blank=True, help_text='백준/solved.ac 아이디 (선택)', max_length=50, null=True)),
            ],
            options={
                'db_table': 'local_account',
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_hash', models.CharField(max_length=200)),
                ('social_id', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=50)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_account',
            },
        ),
    ]
