# Generated by Django 5.2 on 2025-12-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localaccount',
            name='solvedac_handel',
            field=models.CharField(blank=True, help_text='백준/solved.ac 아이디 (선택)', max_length=50, null=True),
        ),
    ]
