# Generated by Django 5.2 on 2025-11-18 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localaccount',
            name='id',
        ),
        migrations.AlterField(
            model_name='localaccount',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='localaccount',
            name='role',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='localaccount',
            name='type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='localaccount',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='local_account', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='localaccount',
            table='local_account',
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(max_length=200)),
                ('social_id', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=50)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_account',
            },
        ),
    ]
