# Generated by Django 5.2 on 2025-12-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localaccount',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='resource/'),
        ),
    ]
