# Generated by Django 5.2 on 2025-11-20 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_localaccount_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localaccount',
            name='type',
        ),
        migrations.AddField(
            model_name='localaccount',
            name='account_type',
            field=models.CharField(default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='localaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='localaccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='localaccount',
            name='role',
            field=models.CharField(choices=[('SP', '학생/학부모'), ('MG', '매니저')], max_length=20),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
