# Generated by Django 5.2 on 2025-11-16 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeekLesson',
            new_name='Lesson',
        ),
    ]
