# Generated by Django 5.2 on 2025-12-06 14:54
# Generated by Django 5.2 on 2025-12-06 15:45
# Generated by Django 5.2.9 on 2025-12-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='dimc_type',
            field=models.CharField(blank=True, choices=[('D', 'D'), ('I', 'I'), ('M', 'M'), ('C', 'C')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('graded', '평가됨'), ('submitted', '제출됨')], default='submitted', max_length=20),
        ),
    ]
