# Generated by Django 5.2 on 2025-11-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_rename_weeklesson_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('graded', '평가됨'), ('submitted', '제출됨')], default='submitted'),
        ),
    ]
