# Generated by Django 5.2 on 2025-12-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_assignment_file_alter_submission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content',
        ),
    ]
