# Generated by Django 5.2 on 2025-12-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('graded', '평가됨'), ('submitted', '제출됨')], default='submitted', max_length=20),
        ),
    ]
