# Generated by Django 5.2 on 2025-12-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_course_dimc_type_alter_submission_status'),
        ('learning', '0003_alter_submission_status'),
    ]

    operations = [
    ]
