# Generated by Django 5.2 on 2025-11-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('new', '생성됨'), ('pending_teacher', '강사 모집'), ('teacher_assigned', '강사 배정완료'), ('enrolling', '학생 모집'), ('in_progress', '강의 진행중'), ('finished', '종료')], default='draft', max_length=20),
        ),
    ]
