# Generated by Django 5.2 on 2025-12-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_remove_lesson_content_alter_submission_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['week', 'order', 'id']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='material_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('etc', 'Etc')], default='pdf', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
