# Generated by Django 5.2 on 2025-12-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_alter_submission_status'),
        ('learning', '0005_remove_lesson_content'),
    ]

    operations = [
    ]
