# Generated by Django 5.2 on 2025-12-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_alter_lesson_options_lesson_material_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['week', 'id']},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='order',
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('graded', '평가됨'), ('submitted', '제출됨')], default='submitted', max_length=20),
        ),
    ]
