# Generated by Django 5.2 on 2025-12-05 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_alter_submission_status'),
        ('learning', '0006_alter_submission_status'),
    ]

    operations = [
    ]
