# Generated by Django 5.2 on 2025-12-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_alter_lesson_options_remove_lesson_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', '제출됨'), ('graded', '평가됨')], default='submitted', max_length=20),
        ),
    ]
