# Generated by Django 5.2 on 2025-12-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_merge_20251208_2045'),
        ('learning', '0006_alter_submission_status'),
    ]

    operations = [
    ]
