# Generated by Django 5.2.9 on 2025-12-06 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_merge_20251205_2342'),
        ('learning', '0008_alter_submission_status'),
    ]

    operations = [
    ]
