# Generated by Django 5.2 on 2025-12-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_alter_submission_status'),
        ('learning', '0008_alter_submission_status'),
    ]

    operations = [
    ]
