# Generated by Django 5.2.9 on 2025-12-06 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_merge_20251206_1416'),
    ]

    operations = [
        # content 컬럼은 이전 단계에서 이미 제거됨. 더 이상 작업 없음.
    ]
