# Generated by Django 5.2 on 2025-11-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_lesson_content_lesson_file_lesson_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', '제출됨'), ('graded', '평가됨')], default='submitted', max_length=20),
        ),
    ]
