# Generated by Django 5.2 on 2025-12-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='resources/course_messages/'),
        ),
    ]
