# Generated by Django 5.2 on 2025-12-03 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolvedAcProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_solved_count', models.PositiveIntegerField(default=0)),
                ('last_solved_count', models.PositiveIntegerField(default=0)),
                ('credited_solved_count', models.PositiveIntegerField(default=0)),
                ('last_handle', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solvedac_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solvedac_progress',
            },
        ),
    ]
