# Generated by Django 5.2 on 2025-12-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_groupfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupfile',
            name='file',
            field=models.FileField(upload_to='group'),
        ),
    ]
