# Generated by Django 5.2 on 2025-12-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_document_block_type'),
        ('group', '0003_alter_groupfile_file'),
    ]

    operations = [
    ]
