# Generated by Django 5.2 on 2025-12-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_merge_20251208_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupfile',
            name='file',
            field=models.FileField(upload_to='resources/group'),
        ),
    ]
