# Generated by Django 5.2 on 2025-12-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_merge_20251208_2008'),
        ('group', '0005_alter_groupfile_file'),
    ]

    operations = [
    ]
