# Generated by Django 5.2 on 2025-12-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_merge_20251208_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='toggle_inner',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='block_type',
            field=models.CharField(choices=[('root', 'Root'), ('page', 'Page'), ('text', 'Text'), ('toggle', 'Toggle'), ('divider', 'Divider')], max_length=20),
        ),
    ]
