# Generated by Django 5.2 on 2025-12-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_merge_20251208_2231'),
        ('group', '0007_remove_document_file_document_toggle_inner_and_more'),
    ]

    operations = [
    ]
